spring:
  jpa:
    show-sql: true
    
de:
  flapdoodle: 
    mongodb:  
      embedded:
        version: 4.0.2  
--- 
spring:
  config:
    activate:
      on-profile:
      - prod
      
  datasource:
    url: jdbc:postgresql:f_members
    username: postgres
    password: changeme
    
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 2000
    
  jpa:
    hibernate:
      ddl-auto: validate
    
    
