spring:
  jpa:
    show-sql: true
    
app:
  dateFormat: dd-MM-yyyy hh:mm:ss    
--- 
spring:
  config:
    activate:
      on-profile:
      - prod
      
  datasource:
    url: jdbc:postgresql:f_members
    username: postgres
    password: changeme
    
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 2000
    
  jpa:
    hibernate:
      ddl-auto: validate
    
    
